server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/jriverah46/microservices
          search-paths: circuit-breaker

  application:
    name: config-service